# Generated by Django 4.1.3 on 2022-11-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Generic', max_length=50)),
                ('producto', models.CharField(help_text='Ingrese materia prima (harina, huevos, levadura, etc.)', max_length=50)),
                ('tipo', models.CharField(help_text="Si corresponde, ejemplo: nombre:harina | tipo:'leudante'/'0000' ", max_length=30)),
                ('fechaIngreso', models.DateField(help_text='Fecha de Ingreso a la fabrica', verbose_name='Fecha de Ingreso')),
                ('fechaVnto', models.DateField(help_text='Fecha indicada en el envase', verbose_name='Fecha de Vencimiento')),
                ('fechaEnvasado', models.DateField(help_text='Fecha indicada en el envase', verbose_name='Fecha de Envasado')),
                ('stockIng', models.PositiveIntegerField(help_text='Cantidad por bultos/fardos/cajas', verbose_name='Stock de ingreso')),
                ('stockDisp', models.PositiveIntegerField(verbose_name='Stock disponible')),
                ('codBulto', models.CharField(blank=True, help_text='Codigo que figura en el bulto ', max_length=13, verbose_name='Codigo de Bulto')),
            ],
            options={
                'ordering': ['fechaVnto'],
            },
        ),
    ]
