# Generated by Django 4.1.2 on 2022-11-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Generic', max_length=50)),
                ('producto', models.CharField(help_text='Ingrese materia prima (harina, huevos, levadura, etc.)', max_length=50)),
                ('tipo', models.CharField(help_text="Si corresponde, ejemplo: nombre:harina | tipo:'leudante'/'0000' ", max_length=30)),
                ('fechaIngreso', models.DateField(help_text='Fecha de Ingreso a la fabrica', verbose_name='Fecha de Ingreso')),
                ('fechaVnto', models.DateField(help_text='Fecha que figura en el envase', verbose_name='Fecha de Vencimiento')),
                ('stockIng', models.PositiveIntegerField(help_text='cantidad por unidad', verbose_name='Stock de ingreso')),
                ('stockDisp', models.PositiveIntegerField(verbose_name='Stock disponible')),
                ('codStock', models.CharField(help_text='Codigo de bulto', max_length=13)),
            ],
            options={
                'ordering': ['fechaVnto'],
            },
        ),
    ]
