# Generated by Django 4.1.2 on 2022-11-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigoBulto',
            field=models.CharField(blank=True, max_length=13, verbose_name='Codigo de bulto'),
        ),
    ]
