# Generated by Django 4.1.3 on 2022-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codStock',
            field=models.CharField(blank=True, help_text='Codigo que figura en el bulto ', max_length=13, verbose_name='Codigo de Bulto'),
        ),
    ]
