# Generated by Django 4.1.3 on 2022-12-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codBulto',
            field=models.CharField(blank=True, help_text='Codigo que figura en el bulto ', max_length=13, verbose_name='Codigo de Bulto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaEnvasado',
            field=models.DateField(default=None, help_text='Fecha indicada en el envase', verbose_name='Fecha de Envasado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaVnto',
            field=models.DateField(help_text='Fecha indicada en el envase', verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockIng',
            field=models.PositiveIntegerField(help_text='Cantidad por bultos/fardos/cajas', verbose_name='Stock de ingreso'),
        ),
    ]
