# Generated by Django 4.1.3 on 2022-12-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_producto_codstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codStock',
            new_name='codBulto',
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaEnvasado',
            field=models.DateField(default=None, help_text='Fecha indicada en el envase', verbose_name='Fecha de Envasado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaVnto',
            field=models.DateField(help_text='Fecha indicada en el envase', verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockIng',
            field=models.PositiveIntegerField(help_text='Cantidad por bultos/fardos/cajas', verbose_name='Stock de ingreso'),
        ),
    ]
