# Generated by Django 4.1.3 on 2022-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_producto_codbulto_producto_fechaenvasado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codBulto',
            field=models.CharField(help_text='Codigo que figura en el bulto ', max_length=13, verbose_name='Codigo de Bulto'),
        ),
    ]
