# Generated by Django 4.1.3 on 2022-12-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_rename_codstock_producto_codbulto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
