# Generated by Django 4.1.4 on 2022-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_alter_producto_imagen_evento_eventmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tiempo_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tiempo_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='start',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='summary',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
