# Generated by Django 4.1.3 on 2022-12-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_remove_evento_created_at_remove_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['fechaIngreso']},
        ),
        migrations.AddField(
            model_name='producto',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
