# Generated by Django 4.1.4 on 2023-01-22 01:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_alter_producto_options_producto_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('empeño', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('dolares', 'Dolares'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=15)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.PositiveIntegerField(choices=[('Tel.', 'Telefono fijo'), ('Cel.', 'Celular')], default='Cel.')),
            ],
        ),
        migrations.CreateModel(
            name='Empeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('comisiones', models.PositiveBigIntegerField(default=0)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso_Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('importe', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=datetime.datetime.today)),
                ('modena', models.CharField(choices=[('Pesos', 'pesos'), ('Dolares', 'dolares')], default='Pesos', max_length=10)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('dolares', 'Dolares'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.empleado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('cuotas', models.IntegerField(choices=[(1, '1'), (3, '3'), (6, '6'), (9, '9'), (12, '12')], default=1)),
                ('fecha_inicio', models.DateField(default=datetime.datetime.today)),
                ('fecha_vnto', models.DateField(default=datetime.datetime.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente')),
            ],
        ),
    ]
