# Generated by Django 4.1.4 on 2023-01-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_cliente_cobro_comision_contacto_empeño_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente'),
        ),
    ]
